os: linux
dist: bionic

language: node_js
node_js:
  - "10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ng lint
  - ng build --prod --base-href https://nodm.github.io/the-weather/
  - replace '%TRAVIS_BUILD_NUMBER%' $TRAVIS_BUILD_NUMBER dist/the-weather/index.html
  - replace '%DARK_SKY_API_KEY%' $DARK_SKY_API_KEY dist/the-weather/index.html
  - replace '%VAPID_PUBLIC_KEY%' $VAPID_PUBLIC_KEY dist/the-weather/index.html
#  - cp dist/the-weather/index.html dist/the-weather/404.html

#deploy:
#  provider: pages
#  skip_cleanup: true
#  token: $GITHUB_TOKEN
#  local_dir: dist/the-weather
#  on:
#    branch: master

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
