export type WeatherSummary = 'clear-day'
  | 'clear-night'
  | 'cloudy'
  | 'fog'
  | 'partly-cloudy-day'
  | 'partly-cloudy-night'
  | 'rain'
  | 'sleet'
  | 'snow'
  | 'thunderstorm'
  | 'tornado'
  | 'wind';
